<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MRD;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class MyTable extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return MyTable
     */
    public static function getRootAsMyTable(ByteBuffer $bb)
    {
        $obj = new MyTable();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function MyTableIdentifier()
    {
        return "MRD1";
    }

    public static function MyTableBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::MyTableIdentifier());
    }

    public static function MyTableExtension()
    {
        return "mrd1";
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return MyTable
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getMyData1()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return sbyte
     */
    public function getMyEnum1()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : \MRD\types::middle;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startMyTable(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return MyTable
     */
    public static function createMyTable(FlatBufferBuilder $builder, $my_data1, $my_enum1)
    {
        $builder->startObject(2);
        self::addMyData1($builder, $my_data1);
        self::addMyEnum1($builder, $my_enum1);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addMyData1(FlatBufferBuilder $builder, $myData1)
    {
        $builder->addOffsetX(0, $myData1, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addMyEnum1(FlatBufferBuilder $builder, $myEnum1)
    {
        $builder->addSbyteX(1, $myEnum1, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endMyTable(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }

    public static function finishMyTableBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset, "MRD1");
    }
}
