// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import { Weapon } from '../../my-game/sample/weapon.js';
export var Equipment;
(function (Equipment) {
    Equipment[Equipment["NONE"] = 0] = "NONE";
    Equipment[Equipment["Weapon"] = 1] = "Weapon";
})(Equipment || (Equipment = {}));
export function unionToEquipment(type, accessor) {
    switch (Equipment[type]) {
        case 'NONE': return null;
        case 'Weapon': return accessor(new Weapon());
        default: return null;
    }
}
export function unionListToEquipment(type, accessor, index) {
    switch (Equipment[type]) {
        case 'NONE': return null;
        case 'Weapon': return accessor(index, new Weapon());
        default: return null;
    }
}
//# sourceMappingURL=equipment.js.map