// automatically generated by the FlatBuffers compiler, do not modify
export class Vec3 {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    x() {
        return this.bb.readFloat32(this.bb_pos);
    }
    y() {
        return this.bb.readFloat32(this.bb_pos + 4);
    }
    z() {
        return this.bb.readFloat32(this.bb_pos + 8);
    }
    static sizeOf() {
        return 12;
    }
    static createVec3(builder, x, y, z) {
        builder.prep(4, 12);
        builder.writeFloat32(z);
        builder.writeFloat32(y);
        builder.writeFloat32(x);
        return builder.offset();
    }
}
