<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MRD;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class message extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return message
     */
    public static function getRootAsmessage(ByteBuffer $bb)
    {
        $obj = new message();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function messageIdentifier()
    {
        return "MRD1";
    }

    public static function messageBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::messageIdentifier());
    }

    public static function messageExtension()
    {
        return "mrd1";
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return message
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    /**
     * @return sbyte
     */
    public function getFrom()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : \MRD\types::middle;
    }

    /**
     * @return sbyte
     */
    public function getTo()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : \MRD\types::middle;
    }

    /**
     * @return sbyte
     */
    public function getAction()
    {
        $o = $this->__offset(8);
        return $o != 0 ? $this->bb->getSbyte($o + $this->bb_pos) : \MRD\actions::connect;
    }

    public function getData()
    {
        $o = $this->__offset(10);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startmessage(FlatBufferBuilder $builder)
    {
        $builder->StartObject(4);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return message
     */
    public static function createmessage(FlatBufferBuilder $builder, $from, $to, $action, $data)
    {
        $builder->startObject(4);
        self::addFrom($builder, $from);
        self::addTo($builder, $to);
        self::addAction($builder, $action);
        self::addData($builder, $data);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addFrom(FlatBufferBuilder $builder, $from)
    {
        $builder->addSbyteX(0, $from, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addTo(FlatBufferBuilder $builder, $to)
    {
        $builder->addSbyteX(1, $to, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param sbyte
     * @return void
     */
    public static function addAction(FlatBufferBuilder $builder, $action)
    {
        $builder->addSbyteX(2, $action, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addData(FlatBufferBuilder $builder, $data)
    {
        $builder->addOffsetX(3, $data, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endmessage(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }

    public static function finishmessageBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset, "MRD1");
    }
}
