<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MRD;

class types
{
    const middle = 0;
    const server = 1;
    const client = 2;

    private static $names = array(
        types::middle=>"middle",
        types::server=>"server",
        types::client=>"client",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
