<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MRD;

class types
{
    const server = 0;
    const client = 1;

    private static $names = array(
        types::server=>"server",
        types::client=>"client",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
