"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.MyTable = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
const flatbuffers = __importStar(require("flatbuffers"));
const types_js_1 = require("../mrd/types.js");
class MyTable {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsMyTable(bb, obj) {
        return (obj || new MyTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsMyTable(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new MyTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static bufferHasIdentifier(bb) {
        return bb.__has_identifier('MRD1');
    }
    myData1(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    myEnum1() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readInt8(this.bb_pos + offset) : types_js_1.types.middle;
    }
    static startMyTable(builder) {
        builder.startObject(2);
    }
    static addMyData1(builder, myData1Offset) {
        builder.addFieldOffset(0, myData1Offset, 0);
    }
    static addMyEnum1(builder, myEnum1) {
        builder.addFieldInt8(1, myEnum1, types_js_1.types.middle);
    }
    static endMyTable(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static finishMyTableBuffer(builder, offset) {
        builder.finish(offset, 'MRD1');
    }
    static finishSizePrefixedMyTableBuffer(builder, offset) {
        builder.finish(offset, 'MRD1', true);
    }
    static createMyTable(builder, myData1Offset, myEnum1) {
        MyTable.startMyTable(builder);
        MyTable.addMyData1(builder, myData1Offset);
        MyTable.addMyEnum1(builder, myEnum1);
        return MyTable.endMyTable(builder);
    }
}
exports.MyTable = MyTable;
