<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MyGame\Sample;

class Equipment
{
    const NONE = 0;
    const Weapon = 1;

    private static $names = array(
        Equipment::NONE=>"NONE",
        Equipment::Weapon=>"Weapon",
    );

    public static function Name($e)
    {
        if (!isset(self::$names[$e])) {
            throw new \Exception();
        }
        return self::$names[$e];
    }
}
