<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MyGame\Sample;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class Weapon extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return Weapon
     */
    public static function getRootAsWeapon(ByteBuffer $bb)
    {
        $obj = new Weapon();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return Weapon
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getName()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @return short
     */
    public function getDamage()
    {
        $o = $this->__offset(6);
        return $o != 0 ? $this->bb->getShort($o + $this->bb_pos) : 0;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startWeapon(FlatBufferBuilder $builder)
    {
        $builder->StartObject(2);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return Weapon
     */
    public static function createWeapon(FlatBufferBuilder $builder, $name, $damage)
    {
        $builder->startObject(2);
        self::addName($builder, $name);
        self::addDamage($builder, $damage);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addName(FlatBufferBuilder $builder, $name)
    {
        $builder->addOffsetX(0, $name, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param short
     * @return void
     */
    public static function addDamage(FlatBufferBuilder $builder, $damage)
    {
        $builder->addShortX(1, $damage, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endWeapon(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }
}
