<?php
// automatically generated by the FlatBuffers compiler, do not modify

namespace MRD;

use \Google\FlatBuffers\Struct;
use \Google\FlatBuffers\Table;
use \Google\FlatBuffers\ByteBuffer;
use \Google\FlatBuffers\FlatBufferBuilder;

class MyTable extends Table
{
    /**
     * @param ByteBuffer $bb
     * @return MyTable
     */
    public static function getRootAsMyTable(ByteBuffer $bb)
    {
        $obj = new MyTable();
        return ($obj->init($bb->getInt($bb->getPosition()) + $bb->getPosition(), $bb));
    }

    public static function MyTableIdentifier()
    {
        return "MRD2";
    }

    public static function MyTableBufferHasIdentifier(ByteBuffer $buf)
    {
        return self::__has_identifier($buf, self::MyTableIdentifier());
    }

    public static function MyTableExtension()
    {
        return "mrd2";
    }

    /**
     * @param int $_i offset
     * @param ByteBuffer $_bb
     * @return MyTable
     **/
    public function init($_i, ByteBuffer $_bb)
    {
        $this->bb_pos = $_i;
        $this->bb = $_bb;
        return $this;
    }

    public function getMyAta()
    {
        $o = $this->__offset(4);
        return $o != 0 ? $this->__string($o + $this->bb_pos) : null;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return void
     */
    public static function startMyTable(FlatBufferBuilder $builder)
    {
        $builder->StartObject(1);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return MyTable
     */
    public static function createMyTable(FlatBufferBuilder $builder, $my_ata)
    {
        $builder->startObject(1);
        self::addMyAta($builder, $my_ata);
        $o = $builder->endObject();
        return $o;
    }

    /**
     * @param FlatBufferBuilder $builder
     * @param StringOffset
     * @return void
     */
    public static function addMyAta(FlatBufferBuilder $builder, $myAta)
    {
        $builder->addOffsetX(0, $myAta, 0);
    }

    /**
     * @param FlatBufferBuilder $builder
     * @return int table offset
     */
    public static function endMyTable(FlatBufferBuilder $builder)
    {
        $o = $builder->endObject();
        return $o;
    }

    public static function finishMyTableBuffer(FlatBufferBuilder $builder, $offset)
    {
        $builder->finish($offset, "MRD2");
    }
}
