"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.Weapon = exports.Vec3 = exports.Monster = exports.Equipment = exports.Color = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var color_js_1 = require("./sample/color.js");
Object.defineProperty(exports, "Color", { enumerable: true, get: function () { return color_js_1.Color; } });
var equipment_js_1 = require("./sample/equipment.js");
Object.defineProperty(exports, "Equipment", { enumerable: true, get: function () { return equipment_js_1.Equipment; } });
var monster_js_1 = require("./sample/monster.js");
Object.defineProperty(exports, "Monster", { enumerable: true, get: function () { return monster_js_1.Monster; } });
var vec3_js_1 = require("./sample/vec3.js");
Object.defineProperty(exports, "Vec3", { enumerable: true, get: function () { return vec3_js_1.Vec3; } });
var weapon_js_1 = require("./sample/weapon.js");
Object.defineProperty(exports, "Weapon", { enumerable: true, get: function () { return weapon_js_1.Weapon; } });
//# sourceMappingURL=sample.js.map